import { requireAuth } from '../_shared/auth.ts'
import { db } from '../_shared/db.ts'
import { sendEmail } from '../_shared/resend.ts'
import { PDFDocument, StandardFonts, rgb } from 'https://esm.sh/pdf-lib@1.17.1'

const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

function json(data: unknown, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: { ...CORS, 'Content-Type': 'application/json' },
  })
}

async function buildPdf(params: {
  projectTitle: string
  trackTitle: string
  dateStr: string
  splits: Array<{ name: string; percentage: number; signedAt: string; signedIp: string }>
  docId: string
}): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create()
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

  const page = pdfDoc.addPage([595, 842])
  const { height } = page.getSize()
  const margin = 60
  const lineH = 18
  let y = height - margin

  function drawText(text: string, opts: { bold?: boolean; size?: number; color?: [number, number, number]; indent?: number }) {
    const size = opts.size ?? 10
    const col = opts.color ? rgb(opts.color[0], opts.color[1], opts.color[2]) : rgb(0, 0, 0)
    page.drawText(text, { x: margin + (opts.indent ?? 0), y, size, font: opts.bold ? boldFont : font, color: col })
  }

  function drawLine() {
    page.drawLine({ start: { x: margin, y: y + 4 }, end: { x: 535, y: y + 4 }, thickness: 0.5, color: rgb(0.7, 0.7, 0.7) })
    y -= lineH
  }

  function skip(n = 1) { y -= lineH * n }

  // Header
  drawText('BS-PASS', { bold: true, size: 18 })
  skip()
  drawText('SPLITS AGREEMENT', { bold: true, size: 13, color: [0.3, 0.3, 0.3] })
  skip(1.5)
  drawLine()
  skip(0.5)

  // Track info
  drawText('Project', { bold: true, size: 9, color: [0.5, 0.5, 0.5] })
  skip()
  drawText(params.projectTitle, { size: 11 })
  skip(1.2)
  drawText('Track', { bold: true, size: 9, color: [0.5, 0.5, 0.5] })
  skip()
  drawText(params.trackTitle, { size: 11 })
  skip(1.2)
  drawText('Generated', { bold: true, size: 9, color: [0.5, 0.5, 0.5] })
  skip()
  drawText(params.dateStr, { size: 10 })
  skip(1.5)
  drawLine()
  skip(0.5)

  // Agreement body
  drawText('REVENUE SPLIT AGREEMENT', { bold: true, size: 11 })
  skip(1.2)
  drawText('The parties listed below agree to the following revenue split for the', { size: 9, color: [0.3, 0.3, 0.3] })
  skip()
  drawText(`track "${params.trackTitle}" as part of the project "${params.projectTitle}".`, { size: 9, color: [0.3, 0.3, 0.3] })
  skip(1.5)

  // Splits table header
  drawText('PARTY', { bold: true, size: 9, color: [0.5, 0.5, 0.5] })
  page.drawText('SHARE', { x: 300, y, size: 9, font: boldFont, color: rgb(0.5, 0.5, 0.5) })
  page.drawText('SIGNED', { x: 420, y, size: 9, font: boldFont, color: rgb(0.5, 0.5, 0.5) })
  skip(1.2)

  for (const s of params.splits) {
    drawText(s.name, { size: 10 })
    page.drawText(`${s.percentage.toFixed(2)}%`, { x: 300, y, size: 10, font, color: rgb(0, 0, 0) })
    page.drawText(s.signedAt, { x: 420, y, size: 9, font, color: rgb(0.3, 0.3, 0.3) })
    skip()
  }

  skip(0.5)
  drawLine()
  skip(0.5)

  // IP log
  drawText('SIGNATURE LOG', { bold: true, size: 11 })
  skip(1.2)
  for (const s of params.splits) {
    drawText(`${s.name}`, { bold: true, size: 9 })
    skip()
    drawText(`Signed: ${s.signedAt}  |  IP: ${s.signedIp}`, { size: 9, color: [0.4, 0.4, 0.4], indent: 10 })
    skip(1.2)
  }

  drawLine()
  skip(0.5)

  // Disclaimer
  drawText('DISCLAIMER', { bold: true, size: 9, color: [0.5, 0.5, 0.5] })
  skip()
  drawText('This document is an informal record of consent generated by BS-PASS.', { size: 8, color: [0.5, 0.5, 0.5] })
  skip()
  drawText('It is not a legally certified e-signature. Consult a music attorney for legally binding agreements.', { size: 8, color: [0.5, 0.5, 0.5] })
  skip(1.5)
  drawText(`Document ID: ${params.docId}`, { size: 8, color: [0.7, 0.7, 0.7] })

  return pdfDoc.save()
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response(null, { headers: CORS })

  try {
    const { userId } = await requireAuth(req)
    const url = new URL(req.url)
    const trackId = req.method === 'GET'
      ? url.searchParams.get('trackId')
      : (await req.json() as { trackId: string }).trackId

    if (!trackId) return json({ error: 'trackId is required' }, 400)

    const supabase = db()

    const { data: track } = await supabase
      .from('tracks')
      .select('id,title,project_id')
      .eq('id', trackId)
      .single()
    if (!track) return json({ error: 'Track not found' }, 404)

    const { data: collab } = await supabase
      .from('collaborators')
      .select('id,is_main_artist')
      .eq('project_id', track.project_id)
      .eq('user_id', userId)
      .is('removed_at', null)
      .maybeSingle()
    if (!collab) return json({ error: 'Forbidden' }, 403)

    const { data: project } = await supabase
      .from('projects')
      .select('title')
      .eq('id', track.project_id)
      .single()

    const { data: splits } = await supabase
      .from('splits')
      .select('id,percentage,split_status,signed_at,signed_ip,collaborators!inner(user_id,profiles:user_id(display_name))')
      .eq('track_id', trackId)

    if (!splits || splits.length === 0) return json({ error: 'No splits found for this track' }, 400)

    const allSigned = splits.every(s => s.split_status === 'signed')
    if (!allSigned) return json({ error: 'All parties must sign before the PDF can be generated' }, 422)

    const now = new Date()
    const dateStr = now.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })

    const splitRows = splits.map(s => {
      const c = s.collaborators as { user_id: string; profiles: { display_name: string } | null }
      return {
        name: c.profiles?.display_name ?? 'Unknown',
        percentage: Number(s.percentage),
        signedAt: s.signed_at ? new Date(s.signed_at).toLocaleDateString('en-US') : 'N/A',
        signedIp: s.signed_ip ?? 'N/A',
        userId: c.user_id,
      }
    })

    const docId = crypto.randomUUID()
    const pdfBytes = await buildPdf({
      projectTitle: project?.title ?? 'Unknown',
      trackTitle: track.title,
      dateStr,
      splits: splitRows,
      docId,
    })

    const filename = `splits-${track.title.replace(/[^a-z0-9]/gi, '-').toLowerCase()}.pdf`

    // Email to all signees
    const userIds = splitRows.map(s => s.userId)
    const { data: authRows } = await supabase.rpc('get_emails_by_user_ids', { p_user_ids: userIds })
    const signeeEmails = (authRows as Array<{ id: string; email: string }> ?? []).map(r => r.email)

    const html = `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:600px;margin:0 auto;padding:20px;color:#1a1a1a;">
  <h2 style="font-size:22px;font-weight:600;margin-bottom:8px;">Splits Agreement — All Signatures Collected</h2>
  <p style="color:#555;margin-bottom:16px;">All parties have signed the splits agreement for <strong>${track.title}</strong> from <strong>${project?.title ?? 'the project'}</strong>.</p>
  <p style="color:#555;margin-bottom:24px;">Your copy of the finalized agreement is attached.</p>
  <p style="color:#888;font-size:13px;">This document is an informal record of consent and is not a legally certified e-signature.</p>
  <p style="color:#bbb;font-size:12px;margin-top:32px;">BS-PASS · AI-powered music project management</p>
</body>
</html>`

    for (const email of signeeEmails) {
      await sendEmail({
        to: email,
        subject: `Splits Agreement Ready — ${track.title}`,
        html,
        text: `All parties have signed the splits agreement for "${track.title}". Your copy is attached.`,
        attachments: [{ filename, content: Array.from(pdfBytes), type: 'application/pdf' }],
      }).catch(e => console.warn(`PDF email to ${email} failed:`, e))
    }

    await supabase.from('audit_logs').insert({
      project_id: track.project_id,
      actor_id: userId,
      actor_type: 'user',
      entity_type: 'splits',
      entity_id: trackId,
      action: 'pdf_generated',
      diff: { track_id: trackId, filename },
    })

    return new Response(pdfBytes, {
      headers: {
        ...CORS,
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Content-Length': String(pdfBytes.length),
      },
    })

  } catch (err) {
    if (err instanceof Response) return err
    const msg = err instanceof Error ? err.message : String(err)
    console.error('splits-generate-pdf unhandled:', msg, err)
    return json({ error: msg }, 500)
  }
})
